In [3]:
import pandas as pd
data = pd.read_csv('heart.csv')
data

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
0,52,1,0,125,212,0,1,168,0,1.0,2,2,3,0
1,53,1,0,140,203,1,0,155,1,3.1,0,0,3,0
2,70,1,0,145,174,0,1,125,1,2.6,0,0,3,0
3,61,1,0,148,203,0,1,161,0,0.0,2,1,3,0
4,62,0,0,138,294,1,1,106,0,1.9,1,3,2,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1020,59,1,1,140,221,0,1,164,1,0.0,2,0,2,1
1021,60,1,0,125,258,0,0,141,1,2.8,1,1,3,0
1022,47,1,0,110,275,0,0,118,1,1.0,1,1,2,0
1023,50,0,0,110,254,0,0,159,0,0.0,2,0,2,1
1024,54,1,0,120,188,0,1,113,0,1.4,1,1,3,0

In [9]:
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler,LabelEncoder
from sklearn.metrics import accuracy_score , classification_report , confusion_matrix
from sklearn.datasets import load_iris
from sklearn.decomposition import PCA
from sklearn.svm import SVC

In [13]:
#preprocess the data
data.dropna(inplace = True)
label_encoders = {}
for col in data.select_dtypes(include=['object']).columns:
    le = LabelEncoder()
    data[col] = le.fit_transform(data[col])
    label_encoders[col] =le

In [17]:
#split dataset into training and testing sets
x = data.drop(columns=['target'])
y = data['target']
x_train , x_test , y_train , y_test = train_test_split(x,y,test_size=0.2,random_state=42)

In [23]:
#standardize features
scaler = StandardScaler()
x_train = scaler.fit_transform(x_train)
x_test = scaler.transform(x_test)

In [25]:
#train & evaluate SVM models
svm_linear = SVC(kernel='linear',C=1)
svm_linear.fit(x_train,y_train)
y_pred_linear = svm_linear.predict(x_test)

In [31]:
# train SVM with poly. kernel 
svm_poly = SVC (kernel='poly' , degree=3,C=1)
svm_poly.fit(x_train,y_train)
y_pred_poly = svm_poly.predict(x_test)

In [33]:
#train SVM with RBF kernel
svm_rbf = SVC(kernel='rbf',C=1,gamma='scale')
svm_rbf.fit(x_train,y_train)
y_pred_rbf = svm_rbf.predict(x_test)

# evaluate model performance

In [36]:
print(f'Linear kernel accuracy: {accuracy_score(y_test,y_pred_linear):.2f}')
print(f'Polynomial kernel accuracy: {accuracy_score(y_test,y_pred_poly):.2f}')
print(f'RBF kernel accuracy: {accuracy_score(y_test,y_pred_rbf):.2f}')

Linear kernel accuracy: 0.81
Polynomial kernel accuracy: 0.91
RBF kernel accuracy: 0.89